Repository elastic/docs, pull requests merged in 2019-12, with the labels that each got.

#1516 Retire 7.4 from the live stack releases
  conf.yaml
Labels: docs, release

#1500 Adds the MS31 build to ESS and Heroku books
  conf.yaml
Labels: release

#1571 [DOCS] Revised notices.
  shared/notices/README.txt
  shared/notices/page_header-OOM.html
  shared/notices/page_header-maintenance.html
Labels: docs, guidelines
