Repository elastic/docs, pull requests merged in 2019-08, with the labels that each got.

#1024 Find "alternative" examples from other repos
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.asciidoc
  build_docs
  build_docs.pl
  conf.yaml
  integtest/html_diff
  integtest/readme_examples/csharp/8a7e0a79b1743d5fd94d79a7106ee930.adoc
  integtest/readme_examples/js/8a7e0a79b1743d5fd94d79a7106ee930.adoc
  integtest/spec/all_books_spec.rb
  integtest/spec/helper/book.rb
  integtest/spec/helper/console_alternative_examples.rb
  integtest/spec/helper/dest.rb
  integtest/spec/single_book_spec.rb
  integtest/spec/spec_helper.rb
  lib/ES/Book.pm
  lib/ES/Source.pm
  lib/ES/Util.pm
  resources/asciidoctor/lib/alternative_language_lookup/alternative.rb
  resources/asciidoctor/lib/alternative_language_lookup/extension.rb
  resources/asciidoctor/lib/alternative_language_lookup/listing.rb
  resources/asciidoctor/lib/alternative_language_lookup/report.rb
  resources/asciidoctor/lib/copy_images/copier.rb
  resources/asciidoctor/lib/edit_me/extension.rb
  resources/asciidoctor/lib/extensions.rb
  resources/asciidoctor/spec/alternative_language_lookup_spec.rb
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/2daa97b0218b60aec4714333e80d7e84.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/5712902c12d9db15d01e8639ece9ec84.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/9e01493a85c06a5100ff712f6b3eead4.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/cf49fef4c762241eee0fa3d1e7fa8b58.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/ded0ba409b7c66489d5833dc6aa5f696.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/fcac4757ba45b9b14f316eb9bda58584.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/included.cs
  resources/asciidoctor/spec/resources/alternative_language_lookup/java/5712902c12d9db15d01e8639ece9ec84.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/js/39f76498cca438ba11af18a7075d24c9.adoc
  resources/asciidoctor/spec/resources/alternative_language_lookup/js/5712902c12d9db15d01e8639ece9ec84.asciidoc
  resources/web/styles.css
  resources/website_common.xsl
Labels: enhancement

#1047 Space TOC lines a bit more
  resources/web/styles.css
Labels: design

#1048 Drop animated scrolling
  resources/web/template.html
Labels: design

#1018 Change current to release-ms-25
  conf.yaml
Labels: docs, release

#1065 Update code and callout style
  resources/web/style/calloutlist.pcss
  resources/web/style/code.pcss
Labels: design

#1072 Correct style on gear icon
  resources/web/styles.pcss
Labels: design

#1092 ECS 1.1.0 docs for release
  conf.yaml
Labels: release

#1094 Switch headings to aktiv grotesk
  resources/web/style/heading.pcss
Labels: design

#1074 Add basic request example to API Reference Template
  shared/api-ref-ex.asciidoc
Labels: docs
