Repository elastic/docs, pull requests merged in 2019-07, with the labels that each got.

#980 [DOCS] Adds continuous data frame related shared attributes.
  shared/attributes.asciidoc
Labels: docs

#1004 Preview: Add a diff endpoint
  integtest/spec/helper/matcher/serve.rb
  integtest/spec/preview_spec.rb
  lib/ES/Util.pm
  package.json
  preview/preview.js
  preview/test.sh
  publish_docker.sh
Labels: preview

#1012 Docs preview: Skip repos we don't own
  preview/__test__/clean.test.js
  preview/clean.js
Labels: preview

#1013 Docs preview: Add a "go away" robots.txt
  integtest/spec/preview_spec.rb
  lib/ES/Util.pm
Labels: preview

#1008 Adds Cloud MS25 to the saas builds
  conf.yaml
Labels: release

#1019 k8s - change current to 0.9
  conf.yaml
Labels: docs, release

#1003 [DOCS] Bump 6.8 version attributes from 6.8.1 to 6.8.2
  shared/versions68.asciidoc
Labels: release

#983 [DOCS] Bump 7.2 version attributes from 7.2.0 to 7.2.1
  shared/versions72.asciidoc
Labels: release

#1020 Adds evaluate data frame analytics API related attributes
  shared/attributes.asciidoc
Labels: docs
