Repository elastic/docs, pull requests merged in 2019-06, with the labels that each got.

#916 Add SIEM Guide to docs landing page
  conf.yaml
  doc_build_aliases.sh
Labels: WIP

#924 Update "For a local repo" section
  README.asciidoc
Labels: docs

#938 [DOCS] Add API reference template example
  shared/api-ref-ex.asciidoc
Labels: docs

#932 Updates shared version attributes
  shared/versions68.asciidoc
Labels: release

#941 [DOCS] Changes the styles of terms in definition lists
  resources/web/styles.css
Labels: design, docs

#928 Remove legacy saas-release from ESS doc builds
  conf.yaml
Labels: docs

#934 docs: update 7.2 to current and released
  conf.yaml
  shared/versions72.asciidoc
Labels: release

#949 [DOCS] Adds optional response codes section to API reference template
  shared/api-ref-ex.asciidoc
  shared/attributes.asciidoc
Labels: docs

#956 Add attribute for 6.8 Elastic Stack Installation & Upgrade Guide
  shared/attributes.asciidoc
Labels: docs

#944 Add observability header to doc landing page
  conf.yaml
Labels: docs
