Repository elastic/docs, pull requests merged in 2019-09, with the labels that each got.

#1134 Restor code style from main.css
  resources/web/style/code.pcss
Labels: design

#1124 Adds regression analysis related attributes to the attributes list
  shared/attributes.asciidoc
Labels: docs

#1146 Updates shared version attributes for 6.8.3
  shared/versions68.asciidoc
Labels: release

#1139 Changes data frame transforms to transforms in the attributes
  shared/attributes.asciidoc
Labels: docs

#1178 Turn on asciidoctor build for Beats documentation
  conf.yaml
Labels: docs

#1206 Update aliases to build beats in asciidoctor
  doc_build_aliases.sh
Labels: docs
