Repository elastic/docs, pull requests merged in 2019-10, with the labels that each got.

#1249 Remove broken link from a deleted topic
  shared/settings.asciidoc
Labels: docs

#1261 [DOCS] Add attributes for SLM
  shared/attributes.asciidoc
Labels: docs, enhancement

#1331 [DOCS] Bump docs for 6.8.4 release
  shared/versions/stack/6.8.asciidoc
Labels: docs, release

#1330 [DOCS] Bump docs for 7.4.1 release
  shared/versions/stack/7.4.asciidoc
Labels: docs, release

#1333 Revert doc version bumps for 6.8.4 and 7.4.1 releases
  shared/versions/stack/6.8.asciidoc
  shared/versions/stack/7.4.asciidoc
Labels: docs, release

#1334 Doc version bumps for 6.8.4 and 7.4.1 releases
  shared/versions/stack/6.8.asciidoc
  shared/versions/stack/7.4.asciidoc
Labels: docs, release

#1260 Adds new data frame analytics related attributes
  shared/attributes.asciidoc
Labels: docs

#1354 Add shared file for discontinued features
  shared/discontinued.asciidoc
Labels: docs

#1360 Add attribute for current version of the Stack Getting Started
  shared/attributes.asciidoc
Labels: docs

#1312 [DOCS] Split Infrastructure Monitoring guide into separate Logs and Metrics docs.
  conf.yaml
  doc_build_aliases.sh
Labels: docs

#1362 Change current for ECE to 2.4
  conf.yaml
Labels: release
