Repository elastic/docs, pull requests merged in 2019-11, with the labels that each got.

#1367 [DOCS] Update custom macro examples for Asciidoctor
  README.asciidoc
Labels: docs, guidelines

#1400 Clean old preview branches
  preview/__test__/clean.test.js
  preview/clean.js
Labels: preview

#1418 Remove 7.x and 7.5 from excludes for processor refactoring
  conf.yaml
Labels: docs

#1435 Added the alternative examples for Cloud
  conf.yaml
Labels: WIP
