Repository elastic/docs, pull requests merged in 2020-11, with the labels that each got.

#1994 Update current version for 7.10
  conf.yaml
  shared/versions/stack/7.10.asciidoc
  shared/versions/stack/current.asciidoc
Labels: release

#2000 [DOCS] Drop 7.9 from stack live
  conf.yaml
Labels: docs, release

#2005 Make ECS 1.7 the current release
  conf.yaml
  shared/versions/stack/master.asciidoc
Labels: ecs, release
