Repository elastic/docs, pull requests merged in 2020-01, with the labels that each got.

#1696 Update the ECS version in master to 1.4
  shared/versions/stack/master.asciidoc
Labels: ecs

#1698 Update ecs_version to 1.4 in 7.x branches
  shared/versions/stack/7.x.asciidoc
Labels: ecs

#1705 Add Github link support to beta and experimental macros
  README.asciidoc
  resources/asciidoctor/lib/care_admonition/extension.rb
  resources/asciidoctor/spec/care_admonition_spec.rb
Labels: docs, enhancement

#1706 Adds language identification related attributes
  shared/attributes.asciidoc
Labels: docs

#1712 [DOCS] Add attribute for EQL guide
  shared/attributes.asciidoc
Labels: docs
