Repository elastic/docs, pull requests merged in 2020-04, with the labels that each got.

#1782 [DOCS] Add function reference template
  shared/attributes.asciidoc
  shared/fn-ref-ex.asciidoc
Labels: docs

#1794 docs: update child_attributes background color
  resources/web/style/child_attributes.pcss
Labels: design, docs

#1797 [DOCS] Add `minor-version` attribute
  shared/versions/stack/5.5.asciidoc
  shared/versions/stack/5.6.asciidoc
  shared/versions/stack/6.0.asciidoc
  shared/versions/stack/6.1.asciidoc
  shared/versions/stack/6.2.asciidoc
  shared/versions/stack/6.3.asciidoc
  shared/versions/stack/6.4.asciidoc
  shared/versions/stack/6.5.asciidoc
  shared/versions/stack/6.6.asciidoc
  shared/versions/stack/6.7.asciidoc
  shared/versions/stack/6.8.asciidoc
  shared/versions/stack/7.0.asciidoc
  shared/versions/stack/7.1.asciidoc
  shared/versions/stack/7.2.asciidoc
  shared/versions/stack/7.3.asciidoc
  shared/versions/stack/7.4.asciidoc
  shared/versions/stack/7.5.asciidoc
  shared/versions/stack/7.6.asciidoc
  shared/versions/stack/7.7.asciidoc
  shared/versions/stack/7.x.asciidoc
  shared/versions/stack/master.asciidoc
Labels: docs

#1800 [DOCS] Correct `minor-version` attribute for 5.5 and 5.6
  shared/versions/stack/5.5.asciidoc
  shared/versions/stack/5.6.asciidoc
Labels: docs

#1803 Correct fallback font for code snippets
  resources/web/style/code.pcss
Labels: bug, design

#1796 [Security]: Add security shared attributes. Remove extra guide
  conf.yaml
  shared/attributes.asciidoc
Labels: docs

#1804 Add kibana observability app names to shared attribute list
  shared/attributes.asciidoc
Labels: docs

#1811 Update `details` style for stacked collapsible sections
  resources/web/style/base_styles.pcss
Labels: design

#1819 [DOCS] Update attributes for multi arg footnotes
  shared/attributes.asciidoc
  shared/fn-ref-ex.asciidoc
Labels: bug, docs
