Repository elastic/docs, pull requests merged in 2020-10, with the labels that each got.

#1973 [DOCS] Adds chunking to Py, Rust, and eland client books
  conf.yaml
  doc_build_aliases.sh
Labels: docs

#1972 Add 7.10 branches to conf.yaml
  conf.yaml
Labels: release

#1979 Add attributes for searchable snapshots.
  shared/attributes.asciidoc
Labels: content

#1983 6.8.13 release
  shared/versions/stack/6.8.asciidoc
Labels: release

#1984 7.9.3 release
  shared/versions/stack/7.9.asciidoc
Labels: release
