Repository elastic/docs, pull requests merged in 2020-05, with the labels that each got.

#1835 Add `dev` care admonition
  README.asciidoc
  resources/asciidoctor/lib/care_admonition/extension.rb
  resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
  resources/asciidoctor/spec/care_admonition_spec.rb
  resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
  resources/web/style/toc.pcss
Labels: enhancement

#1822 Updates for 7.7 release
  conf.yaml
  doc_build_aliases.sh
  shared/versions/stack/7.7.asciidoc
  shared/versions/stack/current.asciidoc
Labels: release

#1829 Bump doc versions
  shared/versions/stack/6.8.asciidoc
Labels: release

#1815 Single-sourced content for cloud and cloud icon
  shared/attributes.asciidoc
  shared/cloud/ess-access-kibana.asciidoc
  shared/cloud/ess-getting-started.asciidoc
  shared/images/logo_cloud.png
  shared/images/logo_cloud.svg
  shared/images/logo_cloud_ece.png
  shared/images/logo_cloud_ece.svg
Labels: docs

#1844 [DOCS] Add `child_attributes` attribute to API reference template
  shared/api-ref-ex.asciidoc
Labels: content, design

#1853 [DOCS] Add short-version attribute
  shared/versions/stack/7.8.asciidoc
  shared/versions/stack/7.x.asciidoc
  shared/versions/stack/master.asciidoc
Labels: docs

#1856 Show better error when Docker missing.
  README.asciidoc
  build_docs
Labels: docs-build

#1841 Remove `v` branches from ecctl docs — DO NOT MERGE YET
  conf.yaml
Labels: versions
