Repository elastic/docs, pull requests merged in 2020-06, with the labels that each got.

#1858 Adds shared attributes section to README
  README.asciidoc
Labels: docs

#1859 Bumps docs version to 7.7.1
  shared/versions/stack/7.7.asciidoc
Labels: docs, release

#1860 Bumps docs version to 6.8.10
  shared/versions/stack/6.8.asciidoc
Labels: docs, release

#1861 docs: Guide order
  conf.yaml
Labels: content

#1862 Add attributes for ingest management
  shared/attributes.asciidoc
Labels: content

#1867 Add an attribute for ingest management
  shared/attributes.asciidoc
Labels: content

#1864 Get Ingest Management docs building
  conf.yaml
  doc_build_aliases.sh
Labels: content

#1869 Add bare version of the ES ref attr & update ES master version.
  shared/attributes.asciidoc
  shared/versions/stack/master.asciidoc
Labels: content

#1873 Sets apm branches for 7.x to master
  shared/attributes.asciidoc
Labels: content

#1874 Set branch for apm-get-started-ref attribute
  shared/attributes.asciidoc
Labels: content

#1881 Revert "Rename .dockerignore files"
  Dockerfile.dockerignore
  air_gapped/Dockerfile.dockerignore
  preview/Dockerfile.dockerignore
Labels: docs-build

#1882 Adds shared version file
  shared/versions/stack/7.9.asciidoc
Labels: versions
