Repository elastic/docs, pull requests merged in 2020-03, with the labels that each got.

#1763 ECS 1.5.0 release
  conf.yaml
Labels: release

#1770 Improve styling for multi-paragraph admonitions
  resources/web/style/admonishment.pcss
Labels: design

#1776 Add attribute for 7.x ES ref docs
  shared/attributes.asciidoc
Labels: docs

#1777 [DOCS] Fix inconsistent deprecated tag in README
  README.asciidoc
Labels: bug, docs

#1788 Add 7.7 doc branches
  conf.yaml
Labels: docs, release

#1778 Bump doc versions
  shared/versions/stack/6.8.asciidoc
  shared/versions/stack/7.6.asciidoc
Labels: release
