Repository elastic/docs, pull requests merged in 2020-12, with the labels that each got.

#2012 7.10.1 release
  shared/versions/stack/7.10.asciidoc
Labels: release

#2019 Add ecs-logging and ecs-dotnet repos
  conf.yaml
Labels: docs-build

#2013 ecctl: Remove beta suffixed branches from listing
  conf.yaml
Labels: enhancement

#2024 Add 7.11 version attributes
  shared/versions/stack/7.11.asciidoc
Labels: release

#2025 Update 7.x shared version to point to 7.12
  shared/versions/stack/7.x.asciidoc
Labels: release

#2026 Add 7.11 branch to doc build
  conf.yaml
Labels: release

#2027 Update stacklive variable
  conf.yaml
Labels: release

#2029 Clarify message on broken links
  integtest/spec/all_books_broken_link_detection_spec.rb
  lib/ES/LinkCheck.pm
Labels: docs-build, link-checking
