Repository elastic/docs, pull requests merged in 2020-09, with the labels that each got.

#1953 Add another location to check for Kibana links
  build_docs.pl
Labels: link-checking

#1951 Updates 7.9 version atts
  shared/versions/stack/7.9.asciidoc
Labels: release

#1957 Prefer remote repos that match the local dir name
  build_docs.pl
Labels: docs-build

#1764 Enable custom "edit" icon for private repos, take 2
  build_docs.pl
  lib/ES/Util.pm
  package.json
  resources/asciidoctor/lib/edit_me/extension.rb
  resources/asciidoctor/spec/edit_me_spec.rb
  resources/web/docs_js/index.js
  resources/web/style/heading.pcss
  resources/web/style/img/edit-me-private.png
  yarn.lock
Labels: feedback

#1954 Updates 7.9 version atts
  shared/versions/stack/7.9.asciidoc
Labels: release
