Repository elastic/docs, pull requests merged in 2020-02, with the labels that each got.

#1724 Add Workplace search docs to the build.
  conf.yaml
Labels: docs

#1731 [DOCS] Remove 7.5 from maintained release branches
  conf.yaml
Labels: docs, release

#1735 Reduce font size of blockquotes
  resources/web/style/base_styles.pcss
Labels: design, docs

#1737 Add standard ESS trial attribute
  shared/attributes.asciidoc
Labels: docs

#1744 Adds shared attributes to PHP API book
  conf.yaml
Labels: enhancement

#1747 Correct CSS for h5 headings
  resources/web/style/heading.pcss
Labels: bug, design

#1690 Updated the title of ESS to "Hosted Elastic Stack"
  conf.yaml
Labels: docs

#1755 Add path for new beats processor
  conf.yaml
Labels: docs

#1756 Remove 7.x from libbeat processor exclude
  conf.yaml
Labels: docs
