Repository elastic/docs, pull requests merged in 2020-07, with the labels that each got.

#1877 [WIP] Add Observability docs
  conf.yaml
  doc_build_aliases.sh
  shared/attributes.asciidoc
Labels: content

#1891 Adding ESS MS 41 branch
  conf.yaml
Labels: release

#1901 [DOCS] [WIP] Add Beats root attribute
  shared/attributes.asciidoc
Labels: docs

#1902 Add attribute for eck html path
  shared/attributes.asciidoc
Labels: docs

#1904 Add more paths for kibana docs
  conf.yaml
Labels: docs-build

#1914 [DOCS] Adding shared checkmark and crossmark icons.
  shared/attributes.asciidoc
  shared/images/icon-no.png
  shared/images/icon-yes.png
Labels: docs

#1912 Add yamale to enforce (and document) a schema for conf.yaml
  Dockerfile
  Makefile
  lib/ES/Book.pm
  schema.yaml
Labels: docs-build

#1915 [DOCS] Moving icons to S3 and adding URLs
  shared/attributes.asciidoc
  shared/images/icon-no.png
  shared/images/icon-yes.png
Labels: docs

#1888 Updates 7.8 version attributes
  shared/versions/stack/7.8.asciidoc
Labels: release

#1887 Updates 6.8 version attributes
  shared/versions/stack/6.8.asciidoc
Labels: release

#1918 Use the "version" rather than "branch" in file paths
  README.asciidoc
  integtest/spec/all_books_change_detection_spec.rb
  integtest/spec/all_books_spec.rb
  integtest/spec/helper/dsl/convert_all.rb
  lib/ES/Book.pm
  schema.yaml
  shared/legacy-attrs.asciidoc
Labels: docs-build
