Repository elastic/docs, pull requests merged in 2020-08, with the labels that each got.

#1929 Remove other places that branch names are used
  integtest/spec/all_books_spec.rb
  integtest/spec/helper/source.rb
  lib/ES/Book.pm
Labels: docs-build

#1909 Allow replacing a book's default title page
  integtest/spec/single_book_spec.rb
  lib/ES/Util.pm
Labels: docs-build

#1935 Don't fail when trying to remove TOC from custom title page
  integtest/spec/all_books_spec.rb
  lib/ES/Book.pm
  lib/ES/Util.pm
Labels: docs-build

#1936 Add 2 new branches in the ECS version selector
  conf.yaml
Labels: ecs

#1938 Add docker logging attributes
  shared/attributes.asciidoc
Labels: docs

#1934 Update versions to 6.8.12
  shared/versions/stack/6.8.asciidoc
Labels: release

#1932 Update current for 7.9.0 release
  conf.yaml
  shared/versions/stack/7.9.asciidoc
  shared/versions/stack/current.asciidoc
Labels: release

#1946 [DOCS] Drop 7.8 from stack live
  conf.yaml
Labels: docs, release

#1947 docs: add timing note to full build docs
  README.asciidoc
Labels: docs

#1944 Make ECS 1.6 current
  conf.yaml
Labels: ecs, release

#1949 Use branch list to decide if branch is new or old
  integtest/spec/all_books_spec.rb
  lib/ES/Book.pm
  schema.yaml
Labels: docs-build
