Repository elastic/docs, pull requests merged in 2021-12, with the labels that each got.

#2300 Add an attribute for "7.last"
  shared/versions/stack/master.asciidoc
Labels: versions

#2311 Point stack 8.0 docs to ECS 8.0 docs
  shared/versions/stack/8.0.asciidoc
Labels: ecs

#2325 Add ECS 8.1 branch
  conf.yaml
  shared/versions/stack/master.asciidoc
Labels: ecs

#2329 [DOCS] Bump version for 7.16.2 and 6.8.22
  shared/versions/stack/6.8.asciidoc
  shared/versions/stack/7.16.asciidoc
Labels: docs, release
