Repository elastic/docs, pull requests merged in 2021-03, with the labels that each got.

#2085 Improve link extraction for Kibana link checking
  build_docs.pl
Labels: link-checking

#2086 Add tests for the Kibana link checking changes in #2085
  integtest/spec/all_books_broken_link_detection_spec.rb
  integtest/spec/all_books_change_detection_spec.rb
Labels: link-checking

#2089 Update version for 6.8.15
  shared/versions/stack/6.8.asciidoc
Labels: release

#2080 Update current version for 7.12
  conf.yaml
  shared/versions/stack/7.11.asciidoc
  shared/versions/stack/7.12.asciidoc
  shared/versions/stack/current.asciidoc
Labels: release

#2091 Add attribute for Cloud-only features
  shared/attributes.asciidoc
Labels: enhancement

#2093 Make ECS 1.9 the current release
  conf.yaml
Labels: ecs, release
