Repository elastic/docs, pull requests merged in 2021-09, with the labels that each got.

#2205 Move shared variables in conf.yaml to the top
  .gitignore
  conf.yaml
  renderconf.py
  schema.yaml
Labels: docs-build

#2213 Hide X-Pack tags on versions 7.11 and later
  integtest/spec/single_book_spec.rb
  resources/asciidoctor/lib/docbook_compat/extension.rb
  resources/asciidoctor/spec/docbook_compat_spec.rb
  shared/versions/stack/7.11.asciidoc
  shared/versions/stack/7.12.asciidoc
  shared/versions/stack/7.13.asciidoc
  shared/versions/stack/7.14.asciidoc
  shared/versions/stack/7.15.asciidoc
  shared/versions/stack/7.x.asciidoc
  shared/versions/stack/master.asciidoc
Labels: docs-build

#2224 Fix building TOCs when version != branch
  lib/ES/Book.pm
Labels: docs-build

#2228 Make ECS 1.12 the current release
  conf.yaml
Labels: release, ecs

#2231 Removes es-java from Java REST Client book sources
  conf.yaml
Labels: docs

#2232 Removes es-java repo resource from Java REST Client doc build alias
  doc_build_aliases.sh
Labels: docs

#2230 Adds new Java API book to Clients
  conf.yaml
Labels: docs

#2233 Adds ES client folder to Java API book sources
  conf.yaml
Labels: docs
