Repository elastic/docs, pull requests merged in 2021-06, with the labels that each got.

#2128 Make ECS 1.10 the current release
  conf.yaml
Labels: ecs, release

#2131 Update docs build for 7.x with changed build-tools organization
  conf.yaml
Labels: docs, docs-build

#2132 Adds more variables to Kibana link checker
  build_docs.pl
  integtest/spec/all_books_broken_link_detection_spec.rb
Labels: link-checking

#2135 Updates versions to 7.13.2
  shared/versions/stack/7.13.asciidoc
Labels: release

#2139 Adds FLEET_DOCS to Kibana link checker
  build_docs.pl
  integtest/spec/all_books_broken_link_detection_spec.rb
Labels: link-checking

#2142 Add attributes for units sections
  shared/attributes.asciidoc
Labels: content
