Repository elastic/docs, pull requests merged in 2021-02, with the labels that each got.

#2053 Updated expired yarn.gpg key
  .docker/apt/keys/yarn.gpg
Labels: docs-build

#2054 Update version for 6.8.14 docs release
  shared/versions/stack/6.8.asciidoc
Labels: release

#2051 Update current version for 7.11
  conf.yaml
  shared/versions/stack/7.10.asciidoc
  shared/versions/stack/7.11.asciidoc
  shared/versions/stack/current.asciidoc
Labels: release

#2058 Change current to MS 52 for ESS
  conf.yaml
Labels: docs

#2062 Make ECS 1.8 the current release
  conf.yaml
Labels: ecs, release

#2068 Add ECS 1.9 branch in prep for release
  conf.yaml
  shared/versions/stack/7.x.asciidoc
  shared/versions/stack/master.asciidoc
Labels: ecs
