Repository elastic/docs, pull requests merged in 2021-07, with the labels that each got.

#2146 Updated units attributes to point to correct anchors
  shared/attributes.asciidoc
Labels: content

#2148 Update 7.13 version to 7.13.3
  shared/versions/stack/7.13.asciidoc
Labels: release

#2149 Update 6.8 version to 6.8.17
  shared/versions/stack/6.8.asciidoc
Labels: release

#2152 Adds shared attribute for the Swimlane connector
  shared/attributes.asciidoc
Labels: content

#2153 Remove extra padding around images
  resources/web/style/img.pcss
Labels: design
