Repository elastic/docs, pull requests merged in 2022-12, with the labels that each got.

#2559 Updates landing page for 8.6
  extra/docs_landing.html
Labels: design, Team:Docs

#2579 Updates SIEM card title
  extra/docs_landing.html
Labels: content

#2583 Fix race condition in link to current docs
  resources/web/docs_js/index.js
Labels: bug
