Repository elastic/docs, pull requests merged in 2022-06, with the labels that each got.

#2456 Set the noindex flag on the Stack Getting Started
  conf.yaml
Labels: content

#2464 [DOCS] Updated Welcome to Elastic attribute to use current
  shared/attributes.asciidoc
Labels: >docs

#2466 8.3 to current for ecs release
  conf.yaml
Labels: ecs

#2467 Add shared attribute to flag features that aren't available yet
  shared/attributes.asciidoc
Labels: content, >docs

#2459 Moved StackGS to Legacy Docs
  conf.yaml
Labels: content, >docs
