Repository elastic/docs, pull requests merged in 2023-05, with the labels that each got.

#2657 Add dropdowns for Ent Search, App Search, Workplace Search books
  resources/asciidoctor/lib/chunker/breadcrumbs.rb
  resources/asciidoctor/lib/chunker/obs_breadcrumbs.rb
  resources/asciidoctor/lib/chunker/search_breadcrumbs.rb
Labels: enhancement

#2677 Fix tabbed widgets
  resources/web/docs_js/components/tabbed_widget.js
Labels: bug

#2687 Updating ECS current for the 8.8 release
  conf.yaml
Labels: release, ecs
